### ISSUE TITLE
Ctrl+X/C/V/A not working on Windows / Linux

### ISSUE THREAD

**Issue by chloebrett** [patrickbrett/mlvet#180]
Cut/copy/paste works from drop-down application menu, but not via keyboard shortcut, on Windows and Linux.

Works as expected on macOS.

**Comment by chloebrett** [comment]
Select all is also not working on win and linux

**Comment by MutazAshhab** [comment]
I did some investigated with this issue and after and the only good finding I found is that nothing is being dispatched to the store when using Ctrl + X/C/V

**Comment by chloebrett** [comment]
Can you test if the IPC call is being invoked at all? I tested and I think it isn't - so it's not a store problem, it's a "back end never even tells the front end" problem

Even worse, I think the menu is never even invoking the click() method on these items (in menu.ts) when the keyboard shortcuts are pressed

**Comment by MutazAshhab** [comment]
I just added log statements inside the copyText, cutText, pasteText, functions and they only get printed (executed) when you click the the menu options and never when you press the keyboard shortcuts.

That means that the IPC call is not being invoked. But could it be caused by the fact that the menu is never invoking the click() method? I dont know.

**Comment by chloebrett** [comment]
I thought as much... can you try the following

1) remove the ctrl+X cut menu item, then change a shortcut that you know DOES work to be ctrl+X. Does that item still work?
2) remove a menu item you know works (e.g. undo), then change the cut shortcut to use that shortcut (e.g. ctrl+Z)

If either/both of these work then we can basically conclude it's a reserved shortcut or something. Haven't found any info about this online though. I'm hoping it doesn't work then we'll likely have something to work with

**Comment by MutazAshhab** [comment]
Alright here is what I found: 

1. I removed `Ctrl + X` and changed `Ctrl + Z` to `Ctrl + X`. And the `undo` action no longer worked.
2. I removed `Ctrl + Z` (undo) and made the accelerator for the cut action `Ctrl + Z`. And it worked.

I guess we can conclude that it is reserved for something. But its weird how you can use `Ctrl + X` on slack and discord...

**Comment by MutazAshhab** [comment]
We could attach event listeners when the user navigates to the editor view. And remove them when the user leaves that view.

However, we should keep the menu items for the shortcuts that do not work since the user might peek at the edit menu and look at the accelerator.

**Comment by MutazAshhab** [comment]
I found a fix, it might come across as smart at first but it isnt very elegant in my opinion.

here is the code for it.

```javascript
  let keys = {};

  window.addEventListener('keydown', (e) => {

    keys[e.key.lower()] = true;

    if (keys['a'] && keys['control']) {
      console.log('select all');
    } else if (keys['v'] && keys['control']) {
      console.log('paste');
    } else if (keys['c'] && keys['control']) {
      console.log('copy');
    } else if (keys['x'] && keys['control']) {
      console.log('cut');
    }
  });

  window.addEventListener('keyup', (e) => {
    keys[e.key.lower()] = false;
  });

  console.log(keys);
```

this code block could be placed in Project.tsx, or we could place it in a function and call call the function in Project.tsx..

The reason I say its not elegant is because we now have to check if the event listeners have been added or not (if the Project.tsx component gets rerendered then it will re-add the event listeners). This could be done in a couple ways.

1. Use the [getEventListeners](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) function and iterate over the results to see if we have already added the event listeners or not.
2. We could have a boolean stored in the global state to indicate whether we have already added the event listeners or not.

**Comment by chloebrett** [comment]
I think we don't need to even do this from within the react context, it can just be globally declared on the front end on load. I'll whip up a prototype tonight

**Comment by chloebrett** [comment]
Didn't get to this tonight, will do sometime this week

**Comment by Irmy** [comment]
Select all also not working - heads up

**Comment by chloebrett** [comment]
> Select all also not working - heads up

Yep known issue - see first comment in this thread
