### ISSUE TITLE
Clipboard gets reset when undoing a paste

### ISSUE THREAD

**Issue by jhea0008** [patrickbrett/mlvet#291]
Steps to reproduce: 

1. Copy a section of text
2. Paste this section somewhere else
3. Undo the paste (control-z)
4. Paste somewhere else

Expected behaviour: 
the clipboard should be kept through the undo and the original text should be pasted in the new location

Actual Behaviour: 
Clipboard gets reset and the second paste does nothing

Tested on MacOS ARM, dev branch commit 81776dd4e81258a4766d487e76941bee539c762c

**Comment by chloebrett** [comment]
I can't replicate this. See the video below of the app performing the expected behaviour (on latest develop at time of writing)

https://user-images.githubusercontent.com/6735055/193449539-7bca80c5-d955-4b3d-8f29-ee8b1bc739b3.mov

The clipboard is (at least as far as I know) unaffected by undos and redos so I was a little surprised you hit this issue - could you maybe post a video?

**Comment by jhea0008** [comment]
Yea looks like this is no longer an issue. Not sure what was causing it earlier. I'm closing it now
